db:
  image: hypriot/rpi-mysql:latest
  environment:
    - MYSQL_ROOT_PASSWORD=secret

sysbench:
  build: .
  command: dockerize -wait http://db:3306 --test-mysql
  environment:
    - FILE_SIZE=8G
    - TABLE_SIZE=1000000
    - TEST_DB=test
    - DB_HOST=db
    - MYSQL_ROOT_PASSWORD=secret
  links:
    - db
